# Generated by Django 5.0.9 on 2026-09-13 08:35

import django.core.validators
from django.db import migrations, models


def create_default_eta_configuration(apps, schema_editor):
    EtaRule = apps.get_model('restaurant', 'EtaRule')

    default_rules = [
        {
            'min_party_size': 1,
            'max_party_size': 2,
            'estimated_wait_minutes': 15,
            'is_active': True,
        },
        {
            'min_party_size': 3,
            'max_party_size': 4,
            'estimated_wait_minutes': 25,
            'is_active': True,
        },
        {
            'min_party_size': 5,
            'max_party_size': None,
            'estimated_wait_minutes': 35,
            'is_active': True,
        },
    ]
    for rule in default_rules:
        EtaRule.objects.get_or_create(
            min_party_size=rule['min_party_size'],
            max_party_size=rule['max_party_size'],
            defaults={
                'estimated_wait_minutes': rule['estimated_wait_minutes'],
                'is_active': rule['is_active'],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_waitlistentry_public_identifier_and_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_party_size', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_wait_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_party_size', 'max_party_size'],
            },
        ),
        migrations.RunPython(
            create_default_eta_configuration,
            migrations.RunPython.noop,
        ),
    ]
