# Generated by Django 5.0.9 on 2026-09-13 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restauranttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_text', models.CharField(blank=True, max_length=255)),
                ('preference_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('arrived', 'Arrived'), ('seated', 'Seated'), ('late_demoted', 'Late/Demoted'), ('cancelled', 'Cancelled'), ('no_show', 'No-show'), ('left', 'Left')], default='waiting', max_length=20)),
                ('priority_metadata', models.JSONField(blank=True, default=dict)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='restaurant.restauranttable')),
            ],
        ),
    ]
