# Generated by Django 5.0.9 on 2026-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_etarule'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='can_accommodate_high_chair',
            field=models.BooleanField(default=False, help_text='Can accommodate a high chair'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='has_accessibility',
            field=models.BooleanField(default=False, help_text='Wheelchair accessible or other accessibility features'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='location',
            field=models.CharField(choices=[('any', 'Any'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='any', help_text='Table location preference match', max_length=20),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='seating_type',
            field=models.CharField(choices=[('standard', 'Standard table'), ('booth', 'Booth'), ('bar', 'Bar seating')], default='standard', help_text='Type of seating at this table', max_length=20),
        ),
    ]
